//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seebon.Weixin.MP.Service.CommonService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultList
    {
        public int id { get; set; }
        public string tousername { get; set; }
        public string fromusername { get; set; }
        public string reqorrep { get; set; }
        public string msgtype { get; set; }
        public string msgid { get; set; }
        public string content { get; set; }
        public string picurl { get; set; }
        public Nullable<double> location_x { get; set; }
        public Nullable<double> location_y { get; set; }
        public Nullable<int> scale { get; set; }
        public string label { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string @event { get; set; }
        public string eventkey { get; set; }
        public string musicurl { get; set; }
        public string hqmusicurl { get; set; }
        public Nullable<int> articlecount { get; set; }
        public string articles { get; set; }
    }
}
