//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seebon.Weixin.MP.Service.CommonService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string custid { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> logintime { get; set; }
        public string clientid { get; set; }
        public Nullable<System.DateTime> connecttime { get; set; }
        public string accountname { get; set; }
        public Nullable<int> logid { get; set; }
    }
}
