//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seebon.Weixin.MP.Service.CommonService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialogRecord
    {
        public int Id { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
        public string Content { get; set; }
        public System.DateTime SendTime { get; set; }
        public bool IsRead { get; set; }
        public string msgtype { get; set; }
        public string media_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string musicurl { get; set; }
        public string hqmusicurl { get; set; }
        public string thumb_media_id { get; set; }
        public string url { get; set; }
        public string picurl { get; set; }
    }
}
