//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seebon.Weixin.MP.Service.CommonService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAnswer
    {
        public int id { get; set; }
        public string key { get; set; }
        public string MsgType { get; set; }
        public string content { get; set; }
        public string MusicUrl { get; set; }
        public string HQMusicUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PicUrl { get; set; }
        public string Url { get; set; }
        public string AccessUser { get; set; }
    }
}
