//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seebon.Weixin.MP.Service.CommonService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string School { get; set; }
        public string Major { get; set; }
        public string Education { get; set; }
        public string Tel { get; set; }
        public string Experience { get; set; }
        public string Guid { get; set; }
    }
}
